# Generated by Django 5.0.4 on 2024-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0002_remove_cartitem_product_id_remove_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
