# Generated by Django 5.0.4 on 2024-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobileno',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
