# Generated by Django 5.0.4 on 2024-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0010_delete_userprofile_cartitem_mobile_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pants_measurement_hip',
            new_name='chudidar_measurement_length',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='pants_measurement_inseam',
            new_name='chudidar_measurement_waist',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='shirt_measurement_coller',
            new_name='coat_measurement_chest',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='shirt_measurement_shirt',
            new_name='coat_measurement_length',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='shirt_measurement_sleeve',
            new_name='estimate_price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='tshirt_measurement_chest',
            new_name='jacket_measurement_chest',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='tshirt_measurement_length',
            new_name='jacket_measurement_length',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='tshirt_measurement_shoulderwidth',
            new_name='kameej_measurement_chest',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='kameej_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='kurta_measurement_chest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='kurta_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='nehrujacket_measurement_chest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='nehrujacket_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pajama_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pajama_measurement_waist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pants_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pathani_measurement_chest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pathani_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shirt_measurement_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Coats', 'Coats'), ('Jackets', 'Jackets'), ('NehruJacket', 'NehruJacket'), ('Kurta', 'Kurta'), ('Kameej', 'Kameej'), ('Pathani', 'Pathani'), ('Pajama', 'Pajama'), ('Chudidar', 'Chudidar')], max_length=255, null=True),
        ),
    ]
