# Generated by Django 5.0.4 on 2024-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0011_rename_pants_measurement_hip_cartitem_chudidar_measurement_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('NehruJacket', 'NehruJacket'), ('Kurta', 'Kurta'), ('Kameej', 'Kameej'), ('Pathani', 'Pathani'), ('Pajama', 'Pajama'), ('Chudidar', 'Chudidar')], max_length=255, null=True),
        ),
    ]
