# Generated by Django 5.0.4 on 2024-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0014_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
