# Generated by Django 5.0.4 on 2024-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0015_cartitem_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cleared',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
