# Generated by Django 5.0.4 on 2024-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0016_cartitem_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cleared',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_address', models.CharField(max_length=100)),
                ('cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='corefunctions.cartitem')),
            ],
        ),
    ]
