# Generated by Django 5.0.4 on 2024-06-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0018_remove_order_items_order_chudidar_measurement_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cleared',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cleared',
        ),
    ]
