# Generated by Django 5.0.4 on 2024-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0026_alter_leave_user_alter_salary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
