# Generated by Django 5.0.4 on 2024-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0028_user_actual_salary_user_base_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.BooleanField(choices=[(None, 'Pending'), (True, 'Approved'), (False, 'Declined')], default=None, null=True),
        ),
    ]
