# Generated by Django 5.0.4 on 2024-06-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corefunctions', '0029_leave_reason_alter_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Coat', 'Coat'), ('Jacket', 'Jacket'), ('NehruJacket', 'NehruJacket'), ('Kurta', 'Kurta'), ('Kameej', 'Kameej'), ('Pathani', 'Pathani'), ('Pajama', 'Pajama'), ('Chudidar', 'Chudidar')], max_length=50)),
                ('chest', models.IntegerField(blank=True, default=0, null=True)),
                ('waist', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='chudidar_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='chudidar_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coat_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='coat_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='jacket_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='jacket_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='kameej_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='kameej_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='kurta_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='kurta_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='nehrujacket_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='nehrujacket_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pajama_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pajama_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pant_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pant_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pathani_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pathani_measurement_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='shirt_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='shirt_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chudidar_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chudidar_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coat_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coat_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jacket_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jacket_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kameej_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kameej_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kurta_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kurta_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nehrujacket_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nehrujacket_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pajama_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pajama_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pant_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pant_measurement_waist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathani_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pathani_measurement_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirt_measurement_chest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shirt_measurement_length',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corefunctions.measurement'),
        ),
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corefunctions.measurement'),
        ),
    ]
