# Generated by Django 5.0.4 on 2024-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0003_alter_d3model_url_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d3model',
            name='url',
            field=models.FileField(upload_to='3dmodels/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='mainfiles/'),
        ),
    ]
